### ISSUE TITLE
Not all dependencies are mentioned in README

### ISSUE THREAD

**Issue by AVHon** [ad044/lain-bootleg-bootleg#9]
In order to get this to work, I had to install the following packages that weren't mentioned:

* [libmpv-dev](https://packages.debian.org/bullseye/libmpv-dev) (mpv itself is mentioned, but not the development headers)
* [opencv-python](https://pypi.org/project/opencv-python/)
* [pefile](https://pypi.org/project/pefile/)

Not too big of a deal, but lain-bootleg-bootleg would be much easier to install and run if the readme mentioned these

**Comment by ad044** [comment]
added, thank you!
